version: '3.4'
services:
  web:
    build: 
      context: .
      target: prodBuild
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    tty: true
    environment:
      - NODE_ENV=production
    command: >
      http-server -p 80 /app
  cypress:
    depends_on: 
      - web
    environment:
      - CYPRESS_baseUrl=http://web:80/
      - CYPRESS_browser=chrome
    build:
      context: .
      target: e2eBuild
      dockerfile: Dockerfile.cypress
    command: ./node_modules/.bin/cypress run
