FROM node:9.11.1

WORKDIR /tmp
COPY package*.json /tmp/
RUN npm install

WORKDIR /usr/src/app
COPY . /usr/src/app/
RUN cp -a /tmp/node_modules /usr/src/app/

ENV NODE_ENV=development
ENV PORT=8085

EXPOSE 8085
CMD [ "npm", "run", "serve" ]
