version: '3.4'
services:
  web:
    container_name: dev
    build:
      context: .
      target: devBuild
      dockerfile: Dockerfile.dev
    ports:
      - "8085:8085"
    volumes:
      - .:/usr/src/app/:rw
    tty: true
    environment:
      - NODE_ENV=development
    command: npm run serve

  cypress: 
    container_name: e2e
    build:
      context: .
      target: e2eBuild
      dockerfile: Dockerfile.cypress
    volumes:
      - .:/usr/src/tests/:rw
    environment:
      - NODE_ENV=docker
    command: ./node_modules/cypress/bin/cypress run