version: '3.2'
services:
  web:
    build: 
      context: .
      # target: prodBuild     # Need support for v3.4 (Docker-Compose)
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    tty: true
    environment:
      - NODE_ENV=production
    command: >
      http-server -p 80 /app
  cypress:
    depends_on: 
      - web
    environment:
      - CYPRESS_baseUrl=http://web:80/
      - CYPRESS_browser=chrome
    build:
      context: .
      # target: e2eBuild    # Need support for v3.4 (Docker-Compose)
      dockerfile: ./cypress/Dockerfile.cypress
    volumes: 
      - type: bind
        source: ./results
        target: /results
