FROM node:9.11.1 as devBuild
WORKDIR /tmp
COPY package*.json /tmp/
RUN CI=true npm install
WORKDIR /usr/src/app
# COPY . /usr/src/app/
RUN cp -a /tmp/node_modules /usr/src/app/
ENV NODE_ENV=development
ENV PORT=8085
EXPOSE 8085
CMD [ "npm", "run", "serve" ]

##
#   This has been replaced by just executing a command against the container
##
# Take from existing build and run tests against it
# FROM node:9.11.1 as testBuild
# WORKDIR /usr/src/app
# COPY --from=devBuild /usr/src/app .
# CMD [ "npm", "run", "test:unit" ]
