version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: 
          name: Building Prod Docker Image
          command: |
            docker build -t martindevnow/vue-docker-cicd -f Dockerfile.production  .
      - run:
          name: Testing Application
          command: |
            docker build -t martindevnow/vue-docker-cicd-test -f Dockerfile.test .
            docker run --rm --name vue-docker-cicd-test-1 martindevnow/vue-docker-cicd-test
    #  - run: 
    #      name: Build and Push Docker Image
    #      command: |
