version: 2
jobs:
  build:
    steps:
      - checkout
      - run: |
          docker build -t martindevnow/vue-docker-cicd .
          docker run -it -p 8080:8080 --rm --name vue-docker-cicd-1 martindevnow/vue-docker-cicd
