version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          docker build -t martindevnow/vue-docker-cicd .
          docker build -t martindevnow/vue-docker-cicd-test -f Dockerfile.test .
          docker run --rm --name vue-docker-cicd-test-1 martindevnow/vue-docker-cicd-test
